#######################################################
#for Kafka
spring:
  kafka: 
    bootstrap-servers=rocket-01.srvs.cloudkafka.com:9094,rocket-02.srvs.cloudkafka.com:9094,rocket-03.srvs.cloudkafka.com:9094
    properties:
      security:
        protocol=SASL_SSL
      sasl:
        mechanism=SCRAM-SHA-256
        jaas:
          config=org.apache.kafka.common.security.scram.ScramLoginModule required username="v4fj0hpd" password="rsBGyqHMfP_n8U4p1O8gA8ptL4BWxtzz";
    consumer:
      auto-offset-reset=earliest      
         

